CREATE TABLE aviso
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid            UUID,
    republica_id    BIGINT                                  NOT NULL,
    titulo          VARCHAR(255),
    mensagem        VARCHAR(255),
    data_publicacao TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    data_edicao     TIMESTAMP(6) WITHOUT TIME ZONE,
    data_remocao    TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT pk_aviso PRIMARY KEY (id)
);

ALTER TABLE aviso
    ADD CONSTRAINT FK_AVISO_ON_REPUBLICA FOREIGN KEY (republica_id) REFERENCES republica (id);