CREATE TABLE tarefa
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              UUID,
    republica_id      BIGINT                                  NOT NULL,
    titulo            VARCHAR(255),
    descricao         VARCHAR(255),
    data_criacao      TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    prazo             TIMESTAMP(6) WITHOUT TIME ZONE,
    data_cancelamento TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT pk_tarefa PRIMARY KEY (id)
);

ALTER TABLE tarefa
    ADD CONSTRAINT FK_TAREFA_ON_REPUBLICA FOREIGN KEY (republica_id) REFERENCES republica (id);