CREATE TABLE IF NOT EXISTS usuarios
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid          UUID,
    nome          VARCHAR(255),
    email         VARCHAR(255),
    senha         VARCHAR(255),
    data_cadastro TIMESTAMP WITHOUT TIME ZONE,
    ativo         BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_usuarios PRIMARY KEY (id)
);
