CREATE TABLE IF NOT EXISTS republica
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid         UUID,
    nome         VARCHAR(255),
    descricao    VARCHAR(255),
    data_criacao TIMESTAMP WITHOUT TIME ZONE,
    ativa        BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_republica PRIMARY KEY (id)
);
