CREATE TABLE IF NOT EXISTS participacao
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid         UUID,
    data_entrada TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_participacao PRIMARY KEY (id)
);
