CREATE TABLE convite
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              UUID,
    codigo            VARCHAR(255),
    data_criacao      TIMESTAMP(6) WITHOUT TIME ZONE,
    data_expiracao    TIMESTAMP(6) WITHOUT TIME ZONE,
    data_cancelamento TIMESTAMP(6) WITHOUT TIME ZONE,
    status            VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_convite PRIMARY KEY (id)
);

ALTER TABLE convite
    ADD CONSTRAINT uc_convite_codigo UNIQUE (codigo);