CREATE TABLE despesa
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              UUID,
    titulo            VARCHAR(255),
    descricao         VARCHAR(255),
    valor_total       DECIMAL                                 NOT NULL,
    data_referencia   date                                    NOT NULL,
    data_vencimento   date                                    NOT NULL,
    data_criacao      TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    data_cancelamento TIMESTAMP(6) WITHOUT TIME ZONE,
    categoria         VARCHAR(255)                            NOT NULL,
    tipo_divisao      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_despesa PRIMARY KEY (id)
);